#! /bin/sh


# Disable Screen Sleep
xset s off -dpms

# Swap Caps With Escape
setxkbmap -option caps:swapescape

# Panel
pgrep -x panel > /dev/null || ~/.config/bspwm/lemonbar/panel &

# Set Wallpapers
feh --bg-fill ~/Pictures/Wallpapers/Solarized/sentre.jpg &

# Polkit
lxpolkit &

# Automount Utility
udiskie &

# Compositor
picom &

# Enable Java Based Apps 
wmname LG3D


pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
