#!/usr/bin/sh

lemon_dir="/home/luis/.config/bspwm/lemonbar"


. ${lemon_dir}/profile

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# Get First Print of Volume
echo "V$(amixer sget Master | tail -n 1 | awk '{print $4}' | tr -d "[]")" > "$PANEL_FIFO" &

# Get Workspace Info
bspc subscribe report > "$PANEL_FIFO" &

# Get Selected Window Title
xtitle -sf 'T%s\n' > "$PANEL_FIFO" & 

# Get Hdd Free Space
while true ; do
    echo "H$(df -h /home | tail -n 1 | awk '{print $4}')"
    sleep 10
done > "$PANEL_FIFO" &

# Get Time
while true ; do
    echo "S$(date +"%l:%M %P")" 
    sleep 10
done > "$PANEL_FIFO" & 

# Ram Info
while true ; do 
    printf "R%s\n" $(free -h | sed -n '2p' | awk '{print $3"/"$2}' | sed 's/i//g')
    sleep 2
done > "$PANEL_FIFO" &

. ${lemon_dir}/panel_colors

${lemon_dir}/panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -u 2 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$FONT_1" -f "$FONT_2" -F "$FOREG" -B "$BACKG" | sh &

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
